name: drdstudio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  tflite_flutter: ^0.10.4
  path_provider: ^2.0.11
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dr_model.tflite

